### ISSUE TITLE
Si estás en una carpeta recién creada, no funciona el deploy

### ISSUE THREAD

**Issue by samuelsolis** [alvar0hurtad0/newton#12]
Es un caso bastante particular, pero supongo que hay que contemplarlo.

Si estamos en master en una carpeta que no existe en pre (por ejemplo, acabas de crear un módulo y estás ahí). Al hacer el drush deploy, cuando se pasa a pre para hacer pull, estás en una carpeta que no existe, y lanza el siguiente mensaje:

*fatal: Unable to read current working directory: No such file or directory*

Es sencillo evitarlo, te sales de la carpeta que acabas de crear, haces el deploy y ya te vuelves a meter y jay. 

Pero se puede arreglar fácil si en el propio deploy nos movemos antes a una carpeta que sepamos que existe y luego volvemos a situarnos donde estábamos.

**Comment by jonhattan** [comment]
Puedes hacer `cd .` para 'resituarte' en una carpeta que se ha borrado y vuelto a crear.

**Comment by alvar0hurtad0** [comment]
Gracias chicos, ya está solucionado con vuestras aportaciones.
